import { Room } from "../core/room";
import { AbsorptionCoefficients } from "../acoustics/rt60";
import { computeRoomFrequencyResponse, Position3D } from "../frequencyResponse";
import { computeUniformityScore, UniformityScore } from "./uniformityScore";

export type SourceConfiguration = ReadonlyArray<{
  readonly position: Position3D;
  readonly gain: number;
  readonly delayMs: number;
  readonly polarity: 1 | -1;
}>;

export type ConfigurationEvaluation = {
  readonly configuration: SourceConfiguration;
  readonly score: UniformityScore;
};

export type OptimizationResult = {
  readonly evaluations: ReadonlyArray<ConfigurationEvaluation>;
  readonly best: ConfigurationEvaluation;
};

/**
 * optimizeConfigurations
 *
 * Evaluates a set of candidate source configurations against a fixed room,
 * listener array, and frequency band, ranks them by combined acoustic
 * quality score, and returns the full evaluation set alongside the
 * best-performing configuration.
 *
 * ============================================================
 * BRUTE-FORCE SEARCH VALIDITY
 * ============================================================
 *
 * This function implements exhaustive evaluation — every candidate
 * configuration is fully simulated and scored independently. This approach
 * is valid and preferred for small-to-moderate candidate sets because:
 *
 *   GLOBAL OPTIMALITY
 *     Exhaustive search guarantees that the returned best configuration
 *     is the true optimum within the candidate set. Gradient-based or
 *     heuristic optimisers can converge to local minima, particularly in
 *     rooms where the combinedScore surface is non-convex due to the
 *     multi-modal interference structure. Brute force has no such failure
 *     mode.
 *
 *   FULL TRANSPARENCY
 *     Every evaluation is preserved in the output. This enables the caller
 *     to inspect the complete score distribution, identify near-optimal
 *     configurations, understand the sensitivity of performance to
 *     configuration changes, and visualise trade-offs between flatness
 *     and uniformity across the candidate space.
 *
 *   DETERMINISM
 *     The result is fully deterministic and reproducible. Given identical
 *     inputs, the output is always identical. No random initialisation,
 *     no convergence tolerance, no iteration budget.
 *
 *   PRACTICAL CANDIDATE SIZES
 *     In loudspeaker layout optimisation, candidate sets are typically
 *     generated by discretising a finite set of positions, gains, delays,
 *     and polarities. For subwoofer arrays this commonly yields tens to
 *     hundreds of candidates — a range where exhaustive evaluation is
 *     computationally practical.
 *
 * ============================================================
 * WHY RANKING BY COMBINED SCORE WORKS
 * ============================================================
 *
 * The combinedScore is a weighted sum of two physically grounded metrics:
 *
 *   combinedScore = flatnessWeight × flatnessDb + uniformityWeight × uniformityDb
 *
 * Both component metrics are in dB, have a natural zero point (perfect
 * flatness or perfect uniformity), and increase monotonically with
 * degradation. Their weighted sum therefore forms a valid scalar objective
 * function over the configuration space:
 *
 *   LOWER combinedScore = BETTER ACOUSTIC PERFORMANCE
 *
 * A configuration with combinedScore = 2.1 objectively outperforms one
 * with combinedScore = 3.7 under the specified weighting. The weights
 * encode the designer's priorities — equal weights treat flatness and
 * uniformity as equally important; unequal weights reflect application-
 * specific requirements (e.g., a cinema may weight uniformity higher
 * than a recording studio).
 *
 * Ranking by ascending combinedScore therefore produces a complete
 * preference ordering over all candidates under the given objective.
 *
 * ============================================================
 * AUTOMATED LAYOUT COMPARISON
 * ============================================================
 *
 * This function enables fully automated comparison of loudspeaker layouts,
 * subwoofer positions, delay configurations, and polarity assignments
 * without manual inspection of frequency response curves. The workflow is:
 *
 *   1. Generate a candidate set by enumerating positions, gains, delays,
 *      and polarities of interest.
 *   2. Call optimizeConfigurations with the desired room, absorption,
 *      listener positions, frequency band, and score weights.
 *   3. Inspect best for the optimal configuration and its score.
 *   4. Inspect evaluations for the full ranking and score distribution.
 *
 * This replaces the traditional workflow of manually auditioning curves,
 * enabling data-driven layout decisions at any scale.
 *
 * ============================================================
 * COMPUTATIONAL COST
 * ============================================================
 *
 * The total computational cost scales as:
 *
 *   O(configurations × listeners × modes × frequencySteps)
 *
 * Where each term contributes multiplicatively:
 *
 *   configurations  — number of candidate source layouts to evaluate.
 *   listeners       — number of spatial sampling positions per evaluation.
 *   modes           — number of room modes below maxFrequencyHz; grows
 *                     roughly as O(f³) per the Weyl formula, so doubling
 *                     maxFrequencyHz increases mode count by ~8×.
 *   frequencySteps  — maxFrequencyHz / frequencyStepHz; finer resolution
 *                     increases this linearly.
 *
 * For large candidate sets or high-resolution analysis, the caller should
 * consider reducing frequencyStepHz, narrowing the analysis band, or
 * pre-filtering candidates before passing to this function.
 *
 * @param room                  - Room defining geometry and boundary surfaces.
 * @param absorption            - Per-surface absorption coefficients.
 * @param configurations        - Candidate source configurations to evaluate.
 * @param listeners             - Listener positions for spatial averaging.
 * @param maxFrequencyHz        - Upper frequency bound for mode enumeration
 *                                and response evaluation (Hz).
 * @param frequencyStepHz       - Frequency resolution of each simulation (Hz).
 * @param minBandFrequencyHz    - Lower bound of the scoring analysis band (Hz).
 * @param maxBandFrequencyHz    - Upper bound of the scoring analysis band (Hz).
 * @param flatnessWeight        - Weight applied to flatnessDb in the combined score.
 * @param uniformityWeight      - Weight applied to uniformityDb in the combined score.
 * @returns OptimizationResult containing all evaluated configurations sorted
 *          by ascending combinedScore, with the best configuration identified.
 */
export function optimizeConfigurations(
  room: Room,
  absorption: AbsorptionCoefficients,
  configurations: ReadonlyArray<SourceConfiguration>,
  listeners: ReadonlyArray<Position3D>,
  maxFrequencyHz: number,
  frequencyStepHz: number,
  minBandFrequencyHz: number,
  maxBandFrequencyHz: number,
  flatnessWeight: number,
  uniformityWeight: number
): OptimizationResult {
  const evaluations: ConfigurationEvaluation[] = configurations.map(
    (configuration) => {
      const response = computeRoomFrequencyResponse(
        room,
        absorption,
        configuration,
        listeners,
        maxFrequencyHz,
        frequencyStepHz
      );

      const score = computeUniformityScore(
        response,
        minBandFrequencyHz,
        maxBandFrequencyHz,
        flatnessWeight,
        uniformityWeight
      );

      return { configuration, score };
    }
  );

  const sorted = evaluations
    .slice()
    .sort((a, b) => a.score.combinedScore - b.score.combinedScore);

  const best = sorted[0];

  return {
    evaluations: sorted,
    best,
  };
}